### ISSUE TITLE
recv() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by MohsinEngineer** [bitvavo/python-bitvavo-api#35]
Versions:

- Python 3.9.9 (pyenv)
- Mac OS Monterey (12.3.1)
- websockets-client version 1.3.3

Here is my code:

```
import websocket
import rel
import traceback

def on_error(ws, error):
    print("on_error")
    print(traceback.format_exc())
    print(error)

def open_connection(url, headers, debug=False):
    websocket.enableTrace(debug)
    sock = websocket.WebSocket()
    sock.connect(url, ssl=True, header=headers, suppress_origin=True)
    ws = websocket.WebSocketApp(url, header=headers, on_open=on_open, on_message=on_message, on_error=on_error, on_close=on_close, socket=sock)
    ws.run_forever(dispatcher=rel)
    rel.signal(2, rel.abort)  # Keyboard Interrupt
    rel.dispatch()
```
The issue:

- when using `WebSocketApp`, socket crashes immediately after connecting.
- keep in mind everything works okay if simple `WebSocket` object is used.
- here is the traceback for the problem caught during `onError()`:

```
Traceback (most recent call last):
  File "/Users/Mohsin/.pyenv/versions/3.9.9/lib/python3.9/site-packages/websocket/_app.py", line 327, in run_forever
    self.sock.connect(
  File "/Users/Mohsin/.pyenv/versions/3.9.9/lib/python3.9/site-packages/websocket/_core.py", line 248, in connect
    self.handshake_response = handshake(self.sock, url, *addrs, **options)
  File "/Users/Mohsin/.pyenv/versions/3.9.9/lib/python3.9/site-packages/websocket/_handshake.py", line 57, in handshake
    status, resp = _get_resp_headers(sock)
  File "/Users/Mohsin/.pyenv/versions/3.9.9/lib/python3.9/site-packages/websocket/_handshake.py", line 146, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/Users/Mohsin/.pyenv/versions/3.9.9/lib/python3.9/site-packages/websocket/_http.py", line 312, in read_headers
    line = recv_line(sock)
  File "/Users/Mohsin/.pyenv/versions/3.9.9/lib/python3.9/site-packages/websocket/_socket.py", line 131, in recv_line
    c = recv(sock, 1)
  File "/Users/Mohsin/.pyenv/versions/3.9.9/lib/python3.9/site-packages/websocket/_socket.py", line 108, in recv
    bytes_ = _recv()
  File "/Users/Mohsin/.pyenv/versions/3.9.9/lib/python3.9/site-packages/websocket/_socket.py", line 87, in _recv
    return sock.recv(bufsize)
TypeError: recv() takes 1 positional argument but 2 were given
```

**Comment by MohsinEngineer** [comment]
Addition:

- if someone can suggest a way where `ssl=True` can be properly passed to the socket created by `WebSocketApp` itself, would be really great.
- I won't have to first create the websocket and then pass it to websocketapp.
